services:

  starrocks-fe-0:
    # image: starrocks/fe-ubuntu:latest
    image: starrocks/fe-ubuntu:3.3-latest
    profiles: ["starrocks"]
    hostname: starrocks-fe-0
    container_name: starrocks-fe-0
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe_entrypoint.sh starrocks-fe-0
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Macau
    networks:
      - development
    ports:
      - "8030:8030"
      - "9020:9020"
      - "9030:9030"
    volumes:
       - ./starrocks/scripts:/opt/starrocks/scripts
       - singleton_fe0_data:/opt/starrocks/fe/meta
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9030"]
      interval: 5s
      timeout: 5s
      retries: 30

  starrocks-be-0:
    #image: starrocks/be-ubuntu:latest
    image: starrocks/be-ubuntu:3.3-latest
    profiles: ["starrocks", "all"]
    hostname: starrocks-be-0
    container_name: starrocks-be-0
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Macau
    networks:
      - development
    ports:
      - "8040:8040"
    depends_on:
      - starrocks-fe-0
    volumes:
      - singleton_be0_data:/opt/starrocks/be/storage



volumes:
  singleton_fe0_data:
    driver: local
  singleton_be0_data:
    driver: local

networks:
  development:
    driver: bridge