services:

  dbt:
    #build: .
    image: ${DEV_IMAGE}
    environment:
      - TZ=Asia/Macau
    #profiles: ["starrocks","mssql","all"]
    networks:
      - development
    volumes:
      - ../../src/.dbt/:/root/.dbt/
      - ../../src:/dbt
    working_dir: /dbt
    entrypoint: /bin/bash
    stdin_open: true
    tty: true




networks:
  development:
    driver: bridge

