tmpl_mssql:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: dev.db
      port: 1433
      database: DWD
      schema: DW_ETL
      user: dbt
      password: Abcd1234
      threads: 4
      encrypt: True
      trust_cert: True